version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nestjs
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: nestjs_db
    depends_on:
      - postgres
    networks:
      - nestjs-network
    restart: always

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
